services: 
  ubuntu:
    build: .
    image: envubuntu:latest
    tty: true
    stdin_open: true
    container_name: EnvUbuntu
    
    volumes:
    - /home/angel/Documents/proyectoenv/:/home/developer/Documents
